version: '3.8'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'      # HTTP
      - '443:443'    # HTTPS
      - '81:81'      # Admin UI
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
  wordpress:
    image: wordpress:latest
    container_name: workreap-wp
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: avertguard.com,www.avertguard.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: avertguard.com,www.avertguard.com
      WORDPRESS_CONFIG_EXTRA: |
        if (!defined('WP_DEBUG')) {
            define('WP_DEBUG', false);
        }
        if (!defined('WP_HOME')) {
            define('WP_HOME', 'https://avertguard.com');
        }
        if (!defined('WP_SITEURL')) {
            define('WP_SITEURL', 'https://avertguard.com');
        }
        define('FORCE_SSL_ADMIN', true);
        $http_x_forwarded_proto = $_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '';
        if ($http_x_forwarded_proto === 'https') {
            $_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - ./wp_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: workreap-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
